     
     name: Deploy Hugo site

     on:
       push:
         branches: [ master ]

     jobs:
       build:
         runs-on: windows-latest
         steps:
           - uses: actions/checkout@v2
             with:
               submodules: False
           - name: Setup Hugo
             uses: peaceiris/actions-hugo@v2
             with:
               hugo-version: '0.147.8'
           - name: Build
             run: hugo --minify
           - name: Deploy
             uses: peaceiris/actions-gh-pages@v3
             with:
               github_token: ${{ secrets.GITHUB_TOKEN }}
               publish_dir: ./public
