name: Deploy Hugo site

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. 拉取源码和主题子模块
      - name: Checkout repository
        uses: actions/checkout@v4 # Use a more recent version
        with:
          submodules: recursive # Use 'recursive' to fetch submodules of submodules if any
          fetch-depth: 0

      # 2. 安装 Hugo
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest' # Use 'latest' or a specific recent version

      # 3. 构建站点
      - name: Build
        run: hugo --minify

      # 4. 部署到 gh-pages
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          # Optional: Add a commit message
          commit_message: "Deploying to gh-pages from @ ${sha}"
